config/routes.rb
Rails.application.routes.draw do
  # get 'page/index'

# NAMESPACE THE PATH

# WHAT WOULD BE the point of namespacing a path and not a controller?
  scope path: '/feeds', as: 'feed' do
    # add path using as, becasue user/:id obstructs the conventional path creation.
    # rails creates a route from the parent scope path and the  get route, but if ther's an id ,
    #  helper url path wont' work.
    get 'user/:id', to: 'feeds#user', as: 'user'
    get 'flat', to: 'feeds#flat'
    get 'aggregated', to: 'feeds#aggregated'
    get 'notification', to: 'feeds#notification'
  end


  resources :items, only: [:new, :create]

  resources :pins, only: [:create, :destroy]

  resources :users, only: [:index]

  resources :follows, only: [:create, :destroy]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/follow.rb
class Follow < ApplicationRecord

  belongs_to :user
  belongs_to :target, class_name: "User"

  validates :target_id, presence: true
  validates :user_id, presence: true


  include StreamRails::Activity
  as_activity

  def activity_object
    self.target
  end

  def activity_notify
    [StreamRails.feed_manager.get_notification_feed(self.target_id)]
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :pins

  # validates_associated :user, presence: false


  def user_pin(user)
    pins.where(user: user).first
  end

end

app/models/pin.rb
class Pin < ApplicationRecord

  belongs_to :user
belongs_to :item

validates :item, presence: true, uniqueness: {scope: :user}
validates :user, presence: true, uniqueness: {scope: :item}

  include StreamRails::Activity
  as_activity

  def actor_object
    self.user
  end

  def activity_object
    self.item
  end
end



# include StreamRails::Activity and as_activity equip Pin with Stream’s functionality. Note that I do not use activity_actor because the default value (self.user) suits us perfectly. We are also leaving activity_verb to the default value of Pin.

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :items
         has_many :follows


   def followed_by(user = nil)
      user.follows.find_by(target_id: id)
   end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  # require 'stream'
  #
  # CLIENT = Stream::Client.new(
  # ENV["STREAM_KEY"],
  # ENV["STREAM_SECRET"],
  # :location => 'us-east'
  # )
  #
  # def client
  #   CLIENT
  # end





  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end




end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :authenticate_user!
  before_action :create_enricher

  def user
    @user = User.find(params[:id])
    feed = StreamRails.feed_manager.get_user_feed(@user.id)
    results = feed.get['results']
    pp results.inspect
    @activities = @enricher.enrich_activities(results)
    pp "User Activities", @activities
  end


  def flat
    feed = StreamRails.feed_manager.get_news_feeds(current_user.id)[:flat]
    results = feed.get['results']
    @activities = @enricher.enrich_activities(results)
    pp "Flat Timeline", @activities

  end


  def aggregated
    feed = StreamRails.feed_manager.get_news_feeds(current_user.id)[:aggregated]
    results = feed.get['results']
    @activities = @enricher.enrich_aggregated_activities(results)
    pp "Aggregated Timeline", @activities
  end

  def notification
    feed = StreamRails.feed_manager.get_notification_feed(current_user.id)
    results = feed.get['results']
    @activities = @enricher.enrich_aggregated_activities(results)
    pp "Notification Aggregated Timeline", @activities

  end





  private

  def create_enricher
    @enricher = StreamRails::Enrich.new
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    follow = Follow.new(follow_params)
    follow.user = current_user
    if follow.save
      StreamRails.feed_manager.follow_user(follow.user_id, follow.target_id)
    end
    flash[:success] = 'Followed!'
    redirect_to users_path
  end

  def destroy
    follow = Follow.find(params[:id])
    if follow.user_id == current_user.id
      follow.destroy!
      StreamRails.feed_manager.unfollow_user(follow.user_id, follow.target_id)
    end
    flash[:success] = 'Unfollowed!'
    redirect_to users_path
  end

  private

  def follow_params
    params.require(:follow).permit(:target_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    @item.save
    puts "#{Item.all}"
    flash[:success] = "Item created!"
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:message, :title)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :authenticate_user!

  def index
    puts "I am pages"
    @items = Item.order('created_at DESC')
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!

  def create
    @pin = Pin.new(pin_params)
    @pin.user = current_user
    if @pin.save!
      # user_feed = client.feed('user', current_user.id)
      # activity_data = { :actor => current_user.id, :verb => 'pin', :object => @pin.item_id}
      # user_feed.add_activity(activity_data)
      flash[:success] = "Pinned!"
      redirect_to root_path
    end
  end

  def destroy
    @pin = Pin.find(params[:id])
    if @pin.destroy
      # user_feed = client.feed('user', current_user.id)
      # user_feed.remove_activity(@pin.item_id, foreign_id=true)
      flash[:success] = "Unpinned!"
      redirect_to root_path
    end
  end


  private

  def pin_params
    params.require(:pin).permit(:item_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
   @users = User.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activity/_follow.html.erb
<div class="well well-sm">
  <p><small class="text-muted"><%= time_ago_in_words activity['time'] %> ago</small></p>

  <p><strong><%= activity['object'].name %></strong> and <strong><%= activity['actor'].name %></strong> are now friends</p>
</div>

app/views/activity/_pin.html.erb
<div class="well well-sm">
  <p><small class="text-muted"><%= time_ago_in_words activity['time'] %> ago</small></p>
  <p>
    <strong><%= activity['actor'].name %></strong> pinned
    <strong><%= activity['object'].title %></strong>
  </p>
</div>

app/views/aggregated_activity/_follow.html.erb
<i class="glyphicon glyphicon-time"></i> <%= time_ago_in_words(activity['updated_at']) %> ago

<% for activity in activity['activities'] %>
  <%= render_activity activity %>
<% end %>

app/views/aggregated_activity/_pin.html.erb
<% if activity['actor_count'] == 1 %>
  <%= activity['activities'][0]['actor'].name %> pinned <%= pluralize(activity['activity_count'], 'item') %>
<% elsif activity['actor_count'] == 2 %>
  <%= activity['activities'][0]['actor'].name %> and <%= activity['activities'][1]['actor'].name %> pinned <%= activity['activity_count'] %> items
<% else %>
  <%= activity['activities'][0]['actor'].name %>, <%= activity['activities'][1]['actor'].name %> and <%= activity['actor_count'].name - 2 %> more pinned <%= activity['activity_count'] %> items
<% end %>

<div class="pull-right">
  <i class="glyphicon glyphicon-time"></i> <%= time_ago_in_words(activity['updated_at']) %> ago
</div>

<% for activity in activity['activities'] %>
  <%= render_activity activity %>
<% end %>

app/views/feeds/aggregated.html.erb
<div class="page-header"><h1>Aggregated feed</h1></div>

<% for activity in @activities %>
  <%= render_activity activity %>
<% end %>

app/views/feeds/flat.html.erb
<div class="page-header"><h1>Flat feed</h1></div>

<% for activity in @activities %>
  <%= render_activity activity %>
<% end %>

app/views/feeds/notification.html.erb
<div class="page-header"><h1>Your notification feed</h1></div>

<% for activity in @activities %>
  <%= render_activity activity %>
<% end %>

app/views/feeds/user.html.erb
<div class="page-header"><h1>My feed</h1></div>

<% for activity in @activities %>
  <%= render_activity activity %>
<% end %>

app/views/items/_item.html.erb
<div class="well well-sm">
  <small class="text-muted"><%= time_ago_in_words item.created_at %> ago</small>
  <h3><%= item.title %></h3>
  <p><%= item.message %></p>

  <%= render "pins/form", item: item %>

</div>

app/views/items/new.html.erb
<div class="page-header"><h1>New items</h1></div>

<%= form_for @item do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :message, class: 'form-control' %>
  </div>

  <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeedMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <nav class="navbar navbar-inverse">
          <div class="container">
            <div class="navbar-header">
              <%= link_to 'FeedMe', root_path, class: 'navbar-brand' %>

            </div>
            <div id="navbar">
              <ul class="nav navbar-nav">

                <li><%= link_to 'Users', users_path %></li>
                <li><%= link_to 'Flat feed', feed_flat_path %></li>
                <li><%= link_to 'Aggregated feed', feed_aggregated_path %></li>
                <li><%= link_to 'Notification feed', feed_notification_path %></li>

                <% if user_signed_in? %>
                  <li><%= link_to 'My feed', feed_user_path(current_user) %></li>
                  <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>

                  <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <i class="glyphicon"></i> <%= current_user.name %><b class="caret"></b>
                    </a>
                  </li>

                <%else%>
                  <li><%= link_to 'Log In', new_user_registration_path%></li>
                <% end %>





              </ul>
            </div>
          </div>
        </nav>


    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>


    </div>





  </body>
</html>

app/views/pages/index.html.erb
<div class="page-header"><h1>Welcome!</h1></div>

<%= link_to "Create New Item", new_item_path %>

<%= render @items %>

app/views/pins/_form.html.erb
<% if item.user_pin(current_user) %>
  <%= button_to "Unpin", pin_path(item.user_pin(current_user)), method: :delete, class: "btn btn-primary btn-sm btn-danger" %>
<% else %>
  <%= form_for :pin, url: pins_path do |f| %>
    <input class="btn btn-primary btn-sm" type="submit" value="Pin">
    <%= f.hidden_field :item_id, value: item.id %>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<h3><%= link_to user.name, feed_user_path(user) %></h3>


<% if user != current_user %>
<% if user.followed_by(current_user) %>
  <%= button_to "Unfollow", follow_path(user.followed_by(current_user)), method: :delete, :class => "btn btn-primary btn-sm btn-danger" %>
<% else %>
  <%= form_for :follow, url: follows_path do |f| %>
    <%= f.hidden_field :target_id, value: user.id %>
    <input class="btn btn-primary btn-sm btn-default" type="submit" value="Follow">
  <% end %>
<% end %>
<% end %>

app/views/users/index.html.erb
<div class="page-header"><h1>Users</h1></div>

<%= render @users %>